"""Helpers for the v2.9 shared/secrets env split."""

from __future__ import annotations

from pathlib import Path


def parse_env_lines(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key:
            values[key] = value.strip()
    return values


def merge_env_files(shared_path: Path, secrets_path: Path) -> str:
    """Return merged env file contents with secrets overriding shared keys."""
    merged = {**parse_env_lines(shared_path), **parse_env_lines(secrets_path)}
    lines = [
        "# Generated by scripts/merge-env-files.py — do not commit.",
        "# Source files: .env.shared + .env.secrets",
        "",
    ]
    for key in sorted(merged):
        lines.append(f"{key}={merged[key]}")
    lines.append("")
    return "\n".join(lines)
